# Generated by Django 3.0.3 on 2020-06-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_goods_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_money',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
