# Generated by Django 3.0.3 on 2020-06-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='extra',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
