# Generated by Django 3.0.3 on 2020-06-04 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderInfo',
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField()),
                ('goods_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('goods_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.OrderInfo')),
            ],
        ),
    ]
