# Generated by Django 3.0.3 on 2020-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('nickname', models.CharField(default='user', max_length=50)),
            ],
        ),
    ]
