# Generated by Django 3.0.3 on 2020-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('info', models.CharField(max_length=500)),
            ],
        ),
    ]
