# Generated by Django 3.0.3 on 2020-06-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_info',
            name='keyword',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
