# Generated by Django 3.0.3 on 2020-06-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_info_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_info',
            name='keyword',
        ),
    ]
