# Generated by Django 3.0.3 on 2020-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(default='male', max_length=10)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
