# Generated by Django 3.0.3 on 2020-06-05 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='A', max_length=5, verbose_name='机器名称')),
                ('CPU', models.CharField(max_length=20)),
                ('Graphics', models.CharField(max_length=20)),
                ('Memory', models.CharField(max_length=20)),
                ('Disk', models.CharField(max_length=20)),
                ('time', models.DateTimeField(verbose_name='预定时间')),
                ('brief', models.TextField(max_length=300, verbose_name='机器信息')),
                ('seats', models.IntegerField(default=0, verbose_name='剩余座位')),
            ],
            options={
                'verbose_name': '机器信息',
                'verbose_name_plural': '机器信息',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='用户名称')),
                ('phone_number', models.CharField(max_length=11, verbose_name='电话号码')),
                ('ticket_name', models.CharField(default='', max_length=30, verbose_name='预定座位信息')),
                ('ticket_time', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 12, 14, 15, 464106), verbose_name='购买车票信息')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
