# Generated by Django 3.0.3 on 2020-06-05 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 14, 19, 46, 538159), verbose_name='购买车票信息'),
        ),
    ]
