# Generated by Django 3.0.3 on 2020-06-06 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200605_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='车票名称')),
                ('num', models.CharField(default='K100', max_length=10, verbose_name='车票编号')),
                ('time', models.DateTimeField(verbose_name='车票出发时间')),
                ('brief', models.TextField(max_length=300, verbose_name='车票信息')),
                ('seats', models.IntegerField(default=0, verbose_name='剩余座位')),
            ],
            options={
                'verbose_name': '车票信息',
                'verbose_name_plural': '车票信息',
            },
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '乘客信息', 'verbose_name_plural': '乘客信息'},
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=10, verbose_name='乘客名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ticket_name',
            field=models.CharField(default=' ', max_length=30, verbose_name='购买车票名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 11, 30, 52, 220306), verbose_name='购买车票时间'),
        ),
    ]
