# Generated by Django 3.0.3 on 2020-06-06 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200606_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': '预定信息', 'verbose_name_plural': '预定信息'},
        ),
        migrations.AddField(
            model_name='tickets',
            name='money',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=10, verbose_name='用户名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ticket_name',
            field=models.CharField(default=' ', max_length=30, verbose_name='预定名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 12, 27, 5, 277637), verbose_name='预定时间'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='brief',
            field=models.TextField(max_length=300, verbose_name='预定信息'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='num',
            field=models.CharField(default='K100', max_length=10, verbose_name='电脑编号'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(verbose_name='预定时间'),
        ),
    ]
