# Generated by Django 3.0.3 on 2020-06-06 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200606_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ticket_money',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 12, 46, 51, 938921), verbose_name='预定时间'),
        ),
    ]
