# Generated by Django 3.0.3 on 2020-06-06 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20200606_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 20, 59, 57, 139611), verbose_name='预定时间'),
        ),
    ]
