# Generated by Django 3.0.3 on 2020-06-06 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20200606_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 22, 56, 26, 83037), verbose_name='预定时间'),
        ),
    ]
