# Generated by Django 3.0.3 on 2020-06-07 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20200606_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 8, 35, 48, 463418), verbose_name='预定时间'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 8, 35, 48, 462418), verbose_name='预定时间'),
        ),
    ]
