# Generated by Django 3.0.3 on 2020-06-07 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20200607_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 9, 23, 11, 914114), verbose_name='预定时间'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 9, 23, 11, 914114), verbose_name='预定时间'),
        ),
    ]
