# Generated by Django 3.0.3 on 2020-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
