# Generated by Django 3.0.3 on 2020-05-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='consume_info',
        ),
    ]
