# Generated by Django 3.0.3 on 2020-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consume', '0002_auto_20200527_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume_info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
