# Generated by Django 3.0.3 on 2020-06-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consume', '0003_auto_20200604_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
